export const authTypes = {
	login: {
		LOGIN_REQUEST: 'LOGIN_REQUEST',
		LOGIN_SUCCESS: 'LOGIN_SUCCESS',
		LOGIN_FAILURE: 'LOGIN_FAILURE'
	},
	logout: {
		USER_LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST'
	}
};
